"""
Profile service: fetch TikTok profile videos and download them with yt-dlp.
Supports Playwright cookie format by converting to Netscape format for yt-dlp.
"""
import asyncio
import json
import os
import re
import tempfile
import uuid
from typing import Optional

import yt_dlp

from backend.config import settings


def extract_product_url(caption: str) -> str:
    """Extract TikTok Shop / affiliate product URL from a caption."""
    if not caption:
        return ""
    # TikTok short links and shop links
    patterns = [
        r'https?://vt\.tiktok\.com/\S+',
        r'https?://vm\.tiktok\.com/\S+',
        r'https?://[^\s]*tiktok\.com/shop[^\s]*',
        r'https?://[^\s]*tiktokshop[^\s]*',
        r'https?://[^\s]+',
    ]
    for pattern in patterns:
        match = re.search(pattern, caption)
        if match:
            url = match.group(0).rstrip('.,;!?)\'"')
            return url
    return ""

COOKIES_FILE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
    "temp",
    "tiktok_cookies.json",
)


def _playwright_cookies_to_netscape(cookies: list) -> str:
    """Convert Playwright cookies JSON format to Netscape cookie format for yt-dlp."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by TikTok Affiliate Tool", ""]
    for c in cookies:
        domain = c.get("domain", "")
        # Netscape format requires domain to start with dot for subdomains
        if not domain.startswith("."):
            domain = "." + domain
        include_subdomains = "TRUE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        # expires: Playwright gives float seconds epoch, yt-dlp expects integer string
        expires = c.get("expires", 0)
        if expires is None or expires == -1:
            expires = 0
        expires = int(expires)
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines)


def _get_netscape_cookies_file() -> Optional[str]:
    """Load Playwright cookies and write to a temp Netscape file. Return path or None."""
    if not os.path.exists(COOKIES_FILE):
        return None
    try:
        with open(COOKIES_FILE) as f:
            cookies = json.load(f)
        if not cookies:
            return None
        netscape_content = _playwright_cookies_to_netscape(cookies)
        tmp = tempfile.NamedTemporaryFile(
            mode="w",
            suffix=".txt",
            prefix="yt_cookies_",
            delete=False,
            encoding="utf-8",
        )
        tmp.write(netscape_content)
        tmp.flush()
        tmp.close()
        return tmp.name
    except Exception:
        return None


async def _get_sec_uid_and_videos_via_api(profile_url: str) -> list:
    """Fetch profile videos using TikTok's internal API + saved cookies."""
    import httpx as _httpx
    import json as _json

    if not os.path.exists(COOKIES_FILE):
        return []

    with open(COOKIES_FILE) as f:
        raw_cookies = _json.load(f)

    # Build cookie dict for httpx (only tiktok.com cookies)
    cookie_dict = {
        c["name"]: c["value"]
        for c in raw_cookies
        if "tiktok.com" in c.get("domain", "")
    }

    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        "Referer": "https://www.tiktok.com/",
    }

    async with _httpx.AsyncClient(
        cookies=cookie_dict, headers=headers, follow_redirects=True, timeout=20
    ) as client:
        # Step 1: Get profile page to extract secUid
        resp = await client.get(profile_url)
        html = resp.text

        # Extract secUid from the page's JSON blob
        sec_uid = ""
        for pattern in [
            r'"secUid"\s*:\s*"([^"]+)"',
            r'"secUID"\s*:\s*"([^"]+)"',
        ]:
            m = re.search(pattern, html)
            if m:
                sec_uid = m.group(1)
                break

        if not sec_uid:
            return []

        # Step 2: Call TikTok's item_list API
        params = {
            "secUid": sec_uid,
            "count": "10",
            "cursor": "0",
            "aid": "1988",
            "app_name": "tiktok_web",
            "device_platform": "web_pc",
        }
        api_resp = await client.get(
            "https://www.tiktok.com/api/post/item_list/",
            params=params,
        )
        try:
            data = api_resp.json()
        except Exception:
            return []

        items = data.get("itemList") or []
        videos = []
        for item in items[:10]:
            vid_id = item.get("id", "")
            author = item.get("author") or {}
            username = author.get("uniqueId") or "user"
            video_url = f"https://www.tiktok.com/@{username}/video/{vid_id}"
            desc = item.get("desc") or ""
            video_info = item.get("video") or {}
            thumb = (
                video_info.get("cover")
                or video_info.get("originCover")
                or ""
            )
            duration = video_info.get("duration", 0)
            videos.append({
                "id": vid_id,
                "url": video_url,
                "title": desc[:120] or "Video TikTok",
                "caption": desc,
                "thumbnail": thumb,
                "duration": int(duration),
                "product_url": extract_product_url(desc),
            })
        return videos


async def _get_video_urls_playwright(profile_url: str) -> list:
    """Use Playwright to get video URLs + thumbnails from a TikTok profile page."""
    from playwright.async_api import async_playwright
    import json as _json

    cookies = None
    if os.path.exists(COOKIES_FILE):
        with open(COOKIES_FILE) as f:
            cookies = _json.load(f)

    video_items = []

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=True,
            args=["--disable-blink-features=AutomationControlled", "--no-sandbox"],
        )
        context = await browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            )
        )
        if cookies:
            await context.add_cookies(cookies)

        page = await context.new_page()

        # Intercept TikTok API to grab full video metadata
        captured = []

        async def on_response(resp):
            url = resp.url
            if any(k in url for k in ["item_list", "user/post", "aweme/v1/feed"]):
                try:
                    data = await resp.json()
                    items = (
                        data.get("itemList")
                        or data.get("items")
                        or data.get("aweme_list")
                        or []
                    )
                    captured.extend(items)
                except Exception:
                    pass

        page.on("response", on_response)

        try:
            await page.goto(profile_url, wait_until="domcontentloaded", timeout=30000)
        except Exception:
            pass

        # Wait and scroll to trigger video list API calls
        await asyncio.sleep(4)
        await page.evaluate("window.scrollTo(0, document.body.scrollHeight / 3)")
        await asyncio.sleep(3)

        if captured:
            for item in captured[:10]:
                vid_id = item.get("id") or item.get("aweme_id", "")
                author = item.get("author") or {}
                username = author.get("uniqueId") or author.get("unique_id") or "user"
                video_url = f"https://www.tiktok.com/@{username}/video/{vid_id}"
                desc = item.get("desc") or ""
                video_info = item.get("video") or {}
                thumb = (
                    video_info.get("cover")
                    or video_info.get("originCover")
                    or video_info.get("dynamicCover")
                    or ""
                )
                duration = video_info.get("duration", 0)
                video_items.append({
                    "id": vid_id,
                    "url": video_url,
                    "title": desc[:120] or "Video TikTok",
                    "caption": desc,
                    "thumbnail": thumb,
                    "duration": int(duration),
                    "product_url": extract_product_url(desc),
                })
        else:
            # DOM fallback: extract video links and thumbnails
            raw = await page.eval_on_selector_all(
                'a[href*="/video/"]',
                """els => els.map(el => {
                    const img = el.querySelector('img');
                    return {
                        href: el.href,
                        thumb: img ? img.src : '',
                        alt: img ? img.alt : ''
                    };
                })"""
            )
            seen = set()
            for item in raw:
                href = item.get("href", "")
                if "/video/" not in href or href in seen:
                    continue
                seen.add(href)
                vid_id = href.split("/video/")[-1].split("?")[0]
                video_items.append({
                    "id": vid_id,
                    "url": href,
                    "title": item.get("alt") or "Video TikTok",
                    "caption": "",
                    "thumbnail": item.get("thumb", ""),
                    "duration": 0,
                    "product_url": "",
                })
                if len(video_items) >= 10:
                    break

        await browser.close()

    return video_items[:10]


async def _enrich_with_ytdlp(video_items: list) -> list:
    """Try to enrich video metadata using yt-dlp for items missing caption/thumbnail."""
    loop = asyncio.get_event_loop()
    enriched = []

    for item in video_items:
        if item.get("caption") and item.get("thumbnail"):
            enriched.append(item)
            continue

        def _fetch_one(url):
            cookie_file = _get_netscape_cookies_file()
            opts = {
                "quiet": True,
                "no_warnings": True,
                "skip_download": True,
                "socket_timeout": 15,
            }
            if cookie_file:
                opts["cookiefile"] = cookie_file
            try:
                with yt_dlp.YoutubeDL(opts) as ydl:
                    info = ydl.extract_info(url, download=False)
                    return info
            except Exception:
                return None
            finally:
                if cookie_file and os.path.exists(cookie_file):
                    try:
                        os.unlink(cookie_file)
                    except Exception:
                        pass

        try:
            info = await asyncio.wait_for(
                loop.run_in_executor(None, _fetch_one, item["url"]),
                timeout=20,
            )
            if info:
                desc = info.get("description") or info.get("title") or ""
                thumb = info.get("thumbnail") or item.get("thumbnail", "")
                item["caption"] = desc
                item["title"] = desc[:120] or item["title"]
                item["thumbnail"] = thumb
                item["duration"] = int(info.get("duration") or item.get("duration") or 0)
                item["product_url"] = extract_product_url(desc)
        except Exception:
            pass

        enriched.append(item)

    return enriched


async def _get_video_meta_tikwm(video_url: str) -> Optional[dict]:
    """Get video metadata from tikwm.com API."""
    import httpx as _httpx
    try:
        async with _httpx.AsyncClient(timeout=15) as client:
            resp = await client.post(
                "https://www.tikwm.com/api/",
                data={"url": video_url, "hd": "1"},
                headers={"User-Agent": "Mozilla/5.0"},
            )
            data = resp.json()
        if data.get("code") != 0:
            return None
        d = data.get("data", {})
        author = d.get("author", {})
        username = author.get("unique_id") or author.get("uniqueId") or "user"
        vid_id = str(d.get("id", ""))
        url = f"https://www.tiktok.com/@{username}/video/{vid_id}"
        desc = d.get("title") or ""
        thumb = d.get("cover") or d.get("origin_cover") or ""
        duration = int(d.get("duration") or 0)
        return {
            "id": vid_id,
            "url": url,
            "title": desc[:120] or "Video TikTok",
            "caption": desc,
            "thumbnail": thumb,
            "duration": duration,
            "product_url": extract_product_url(desc),
        }
    except Exception:
        return None


async def _get_profile_videos_tikwm(profile_url: str) -> list:
    """Get profile videos via tikwm.com API (fallback when yt-dlp fails)."""
    import httpx as _httpx
    # Extract username from URL
    m = re.search(r'tiktok\.com/@([^/?]+)', profile_url)
    if not m:
        return []
    username = m.group(1)
    try:
        async with _httpx.AsyncClient(timeout=20) as client:
            resp = await client.get(
                f"https://www.tikwm.com/api/user/posts",
                params={"unique_id": username, "count": "10", "cursor": "0"},
                headers={"User-Agent": "Mozilla/5.0"},
            )
            data = resp.json()
        if data.get("code") != 0:
            return []
        items = data.get("data", {}).get("videos") or []
        videos = []
        for d in items[:10]:
            vid_id = str(d.get("video_id") or d.get("id") or "")
            url = f"https://www.tiktok.com/@{username}/video/{vid_id}"
            desc = d.get("title") or ""
            thumb = d.get("cover") or d.get("origin_cover") or ""
            duration = int(d.get("duration") or 0)
            videos.append({
                "id": vid_id,
                "url": url,
                "title": desc[:120] or "Video TikTok",
                "caption": desc,
                "thumbnail": thumb,
                "duration": duration,
                "product_url": extract_product_url(desc),
            })
        return videos
    except Exception:
        return []


async def get_profile_videos(profile_url: str) -> list:
    """Fetch up to 10 most recent videos from a TikTok profile."""
    loop = asyncio.get_event_loop()

    # Capture video IDs that yt-dlp finds during extraction
    captured_ids: list = []

    class _IDCapture:
        def debug(self, msg):
            m = re.search(r'\[tiktok(?::user)?\] (\d{15,20}): Downloading', msg)
            if m:
                vid_id = m.group(1)
                if vid_id not in captured_ids:
                    captured_ids.append(vid_id)
        def warning(self, msg): pass
        def error(self, msg): pass

    def _fetch():
        cookie_file = _get_netscape_cookies_file()
        ydl_opts = {
            "quiet": True,
            "no_warnings": True,
            "extract_flat": True,
            "playlist_items": "1-10",
            "ignoreerrors": True,
            "socket_timeout": 30,
            "retries": 3,
            "logger": _IDCapture(),
        }
        if cookie_file:
            ydl_opts["cookiefile"] = cookie_file
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(profile_url, download=False)
        finally:
            if cookie_file and os.path.exists(cookie_file):
                try:
                    os.unlink(cookie_file)
                except Exception:
                    pass

        if not info:
            return []

        entries = info.get("entries") or []
        videos = []
        for entry in entries[:10]:
            if not entry:
                continue
            vid_id = entry.get("id", "")
            uploader = entry.get("uploader_id") or entry.get("channel_id") or "user"
            if uploader and not uploader.startswith("@"):
                uploader = "@" + uploader
            video_url = (
                entry.get("webpage_url")
                or entry.get("url")
                or f"https://www.tiktok.com/{uploader}/video/{vid_id}"
            )
            desc = entry.get("description") or entry.get("title") or ""
            thumbnail = entry.get("thumbnail") or ""
            if not thumbnail and entry.get("thumbnails"):
                thumbs = sorted(
                    [t for t in entry["thumbnails"] if t.get("url")],
                    key=lambda t: t.get("width") or 0,
                    reverse=True,
                )
                if thumbs:
                    thumbnail = thumbs[0]["url"]
            videos.append({
                "id": vid_id,
                "url": video_url,
                "title": desc[:120] or "Video TikTok",
                "caption": desc,
                "thumbnail": thumbnail,
                "duration": int(entry.get("duration") or 0),
                "product_url": extract_product_url(desc),
            })
        return videos

    videos = await loop.run_in_executor(None, _fetch)

    if videos:
        return videos

    # yt-dlp playlist extraction failed — try tikwm.com API first
    videos = await _get_profile_videos_tikwm(profile_url)
    if videos:
        return videos

    # Last resort: use captured video IDs from yt-dlp logs + tikwm metadata
    if captured_ids:
        m = re.search(r'tiktok\.com/@([^/?]+)', profile_url)
        username = m.group(1) if m else "user"
        tasks = [
            _get_video_meta_tikwm(f"https://www.tiktok.com/@{username}/video/{vid_id}")
            for vid_id in captured_ids[:10]
        ]
        results = await asyncio.gather(*tasks, return_exceptions=True)
        videos = [r for r in results if isinstance(r, dict)]
        if videos:
            return videos

    raise RuntimeError(
        "Không lấy được video. Kiểm tra lại link profile (dạng https://www.tiktok.com/@username)"
    )


async def _UNUSED_get_profile_videos_playwright(profile_url: str) -> list:
    """Playwright fallback — kept for reference."""
    from playwright.async_api import async_playwright
    import json as _json

    cookies = []
    if os.path.exists(COOKIES_FILE):
        with open(COOKIES_FILE) as f:
            cookies = _json.load(f)

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=True,
            args=["--disable-blink-features=AutomationControlled", "--no-sandbox"],
        )
        context = await browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            )
        )
        if cookies:
            await context.add_cookies(cookies)

        page = await context.new_page()

        try:
            await page.goto(profile_url, wait_until="domcontentloaded", timeout=30000)
        except Exception:
            pass
        await asyncio.sleep(5)

        # Step 1: Extract secUid from page data via JS
        sec_uid = await page.evaluate("""() => {
            try {
                const s = document.getElementById('__UNIVERSAL_DATA_FOR_REHYDRATION__');
                if (s) {
                    const d = JSON.parse(s.textContent);
                    const scope = d['__DEFAULT_SCOPE__'] || {};
                    const userDetail = scope['webapp.user-detail'] || {};
                    const userInfo = userDetail['userInfo'] || {};
                    const user = userInfo['user'] || {};
                    if (user.secUid) return user.secUid;
                }
            } catch(e) {}
            // Try NEXT_DATA
            try {
                const n = document.getElementById('__NEXT_DATA__');
                if (n) {
                    const d = JSON.parse(n.textContent);
                    const props = d.props?.pageProps?.userInfo?.user || {};
                    if (props.secUid) return props.secUid;
                }
            } catch(e) {}
            // Try __sigi_state__
            try {
                const sig = window['__sigi_state__'] || window['SIGI_STATE'];
                if (sig) {
                    const users = sig.UserModule?.users || {};
                    const keys = Object.keys(users);
                    if (keys.length > 0) return users[keys[0]].secUid || '';
                }
            } catch(e) {}
            return '';
        }""")

        videos = []

        if sec_uid:
            # Step 2: Call TikTok API from inside the browser (cookies included automatically)
            result = await page.evaluate(f"""async () => {{
                try {{
                    const resp = await fetch(
                        'https://www.tiktok.com/api/post/item_list/?aid=1988&count=10&secUid={sec_uid}&cursor=0&app_name=tiktok_web&device_platform=web_pc',
                        {{credentials: 'include'}}
                    );
                    return await resp.json();
                }} catch(e) {{
                    return null;
                }}
            }}""")

            if result and result.get("itemList"):
                for item in result["itemList"][:10]:
                    vid_id = item.get("id", "")
                    author = item.get("author") or {}
                    username = author.get("uniqueId") or "user"
                    url = f"https://www.tiktok.com/@{username}/video/{vid_id}"
                    desc = item.get("desc") or ""
                    vinfo = item.get("video") or {}
                    thumb = vinfo.get("cover") or vinfo.get("originCover") or ""
                    duration = vinfo.get("duration") or 0
                    videos.append({
                        "id": vid_id, "url": url,
                        "title": desc[:120] or "Video TikTok",
                        "caption": desc, "thumbnail": thumb,
                        "duration": int(duration),
                        "product_url": extract_product_url(desc),
                    })

        if not videos:
            # Fallback: scrape video links from DOM
            await page.evaluate("window.scrollTo(0, 500)")
            await asyncio.sleep(2)
            raw = await page.eval_on_selector_all(
                'a[href*="/video/"]',
                """els => [...new Set(els.map(e => e.href))].filter(h => h.includes('/video/')).slice(0, 10)
                   .map(href => ({
                       href,
                       thumb: document.querySelector(`a[href="${href}"] img`)?.src || ''
                   }))"""
            )
            for item in raw:
                href = item.get("href", "")
                vid_id = href.split("/video/")[-1].split("?")[0]
                videos.append({
                    "id": vid_id, "url": href,
                    "title": "Video TikTok", "caption": "",
                    "thumbnail": item.get("thumb", ""),
                    "duration": 0, "product_url": "",
                })

        await browser.close()

    if not videos:
        raise RuntimeError(
            "Không lấy được video từ profile này. "
            "Hãy chắc chắn link đúng dạng https://www.tiktok.com/@username"
        )
    return videos[:10]


async def _download_via_api(video_url: str, final_path: str) -> bool:
    """Fallback: download TikTok video via tikwm.com API when yt-dlp fails."""
    import httpx as _httpx
    clean_url = video_url.split("?")[0]
    try:
        async with _httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                "https://www.tikwm.com/api/",
                data={"url": clean_url, "hd": "1"},
                headers={"User-Agent": "Mozilla/5.0"},
            )
            data = resp.json()
        if data.get("code") != 0:
            return False
        video_dl_url = data.get("data", {}).get("hdplay") or data.get("data", {}).get("play")
        if not video_dl_url:
            return False
        async with _httpx.AsyncClient(timeout=120, follow_redirects=True) as client:
            dl = await client.get(video_dl_url, headers={"User-Agent": "Mozilla/5.0"})
            dl.raise_for_status()
            with open(final_path, "wb") as f:
                f.write(dl.content)
        return os.path.getsize(final_path) > 10000
    except Exception:
        return False


def _convert_to_h264(src_path: str, dst_path: str) -> bool:
    """Re-encode video to H.264/AAC so TikTok Studio accepts it without issues."""
    import subprocess
    try:
        result = subprocess.run(
            [
                "ffmpeg", "-y", "-i", src_path,
                "-c:v", "libx264", "-preset", "fast", "-crf", "23",
                "-c:a", "aac", "-b:a", "128k",
                "-movflags", "+faststart",
                dst_path,
            ],
            capture_output=True,
            timeout=300,
        )
        return result.returncode == 0 and os.path.exists(dst_path) and os.path.getsize(dst_path) > 10000
    except Exception:
        return False


def _needs_h264_conversion(path: str) -> bool:
    """Return True if the video is not H.264 (e.g. HEVC/H.265)."""
    import subprocess
    try:
        result = subprocess.run(
            ["ffprobe", "-v", "quiet", "-select_streams", "v:0",
             "-show_entries", "stream=codec_name", "-of", "default=nw=1:nk=1", path],
            capture_output=True, text=True, timeout=15,
        )
        codec = result.stdout.strip().lower()
        return codec not in ("h264", "avc", "")
    except Exception:
        return False


async def download_video(video_url: str) -> str:
    """Download a TikTok video without watermark, return local file path (H.264)."""
    loop = asyncio.get_event_loop()
    file_id = uuid.uuid4().hex[:10]
    output_template = os.path.join(settings.TEMP_DIR, f"dl_{file_id}.%(ext)s")
    final_path = os.path.join(settings.TEMP_DIR, f"dl_{file_id}.mp4")
    clean_url = video_url.split("?")[0]

    def _download_ytdlp():
        cookie_file = _get_netscape_cookies_file()
        ydl_opts = {
            "quiet": True,
            "no_warnings": True,
            "outtmpl": output_template,
            "format": "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
            "merge_output_format": "mp4",
            "socket_timeout": 60,
            "retries": 3,
            "postprocessors": [{"key": "FFmpegVideoConvertor", "preferedformat": "mp4"}],
        }
        if cookie_file:
            ydl_opts["cookiefile"] = cookie_file
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([clean_url])
        finally:
            if cookie_file and os.path.exists(cookie_file):
                try:
                    os.unlink(cookie_file)
                except Exception:
                    pass

        if os.path.exists(final_path):
            return True
        for ext in ("mp4", "webm", "mkv", "mov", "avi"):
            candidate = os.path.join(settings.TEMP_DIR, f"dl_{file_id}.{ext}")
            if os.path.exists(candidate):
                if candidate != final_path:
                    os.rename(candidate, final_path)
                return True
        return False

    # Try yt-dlp first
    try:
        ok = await loop.run_in_executor(None, _download_ytdlp)
        if ok and os.path.exists(final_path):
            pass  # fall through to H.264 check below
        else:
            raise RuntimeError("yt-dlp download failed")
    except Exception:
        # Fallback: tikwm.com API
        ok = await _download_via_api(clean_url, final_path)
        if not ok:
            raise RuntimeError(f"Tải video thất bại. Video có thể bị hạn chế hoặc đã bị xoá: {clean_url}")

    # Convert to H.264 if needed (tikwm often returns HEVC which can't be viewed/uploaded reliably)
    if _needs_h264_conversion(final_path):
        h264_path = os.path.join(settings.TEMP_DIR, f"dl_{file_id}_h264.mp4")
        converted = await loop.run_in_executor(None, _convert_to_h264, final_path, h264_path)
        if converted:
            os.remove(final_path)
            os.rename(h264_path, final_path)

    return final_path
